[package]
name = "edgeagent-messaging-nats"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
async-nats.workspace = true
edgeagent-contracts.workspace = true
edgeagent-messaging.workspace = true

[dev-dependencies]
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
